### ISSUE TITLE
Add contains property  to entity

### ISSUE THREAD

**Issue by yehudarav** [argosp/trialdash#172]
Add a property 'contains' to every device that lists the devices it contains. 

The property is trial dependent.

**Comment by YehuditGrinwald** [comment]
for developer:  
now: Trial has array of entities object  (entity is  a key, properties, typeKey).
should be: Trial has array of Trial-entities ids. Trial-entity is an object like above **plus** contains- array of Trial-entities ids.
get the data need recursive function.

@yehudarav Because that restructure the data save by difference way.  should  we support old data or can we delete it?

**Comment by yehudarav** [comment]
You can delete it .

**Comment by YehuditGrinwald** [comment]
For developer: Check TrialMutationUpdate to see how hierarchy data will save correctly

**Comment by YehuditGrinwald** [comment]
[use this mutation](https://github.com/argosp/trialdash/issues/182)

**Comment by YehuditGrinwald** [comment]
[issue#182 is duplicate so I close 182](https://github.com/argosp/trialdash/issues/182)

**Comment by YehuditGrinwald** [comment]
@yehudarav done on client & server.  
@YehuditGrinwald Remains: To implement the design of the  contains array view

**Comment by YehuditGrinwald** [comment]
@yehudarav Currently When  entity added to entity. we add that entity to to the general entities list of the trial.  
What should happen when remove entity from contains array ?

**Comment by yehudarav** [comment]
It could stay there. There is no harm in it.

**Comment by yehudarav** [comment]
It could stay in the trial. I don't think you need to do anything.
