### ISSUE TITLE
Edit experiment map and images inputs

### ISSUE THREAD

**Issue by YehuditGrinwald** [argosp/trialdash#88]
In Edit experiment form - add an options to choose  map/ image with this inputs:

1.image url as string
2. bounds of 4 numeric inputs as an array.
3. attribution as string
4. image nickname as string

@yehudarav  please update the issue by your exact requirements and provide ui screen.

**Comment by yehudarav** [comment]
Hi, 

In the edit experiment form we load the images. There is no need to load or to state that a map is required (it will be the default location). 

The inputs are: 
1. Image  - I think we would have to load the image to the DB. Otherwise, I don't know how the user could add or remove images from the experiment. 
2. The scale/bounds of an image should be: 
    1) x,y (in pixels) that denote the 0,0. 
    2) The number of meters a single pixel represents. 

    So overall, 3 numbers. 
3. The image name - this name will be used in the combo box of the location. 

* The UI will present a thumbnail of the image. 
*  It would be possible to add/remove locations.

**Comment by YehuditGrinwald** [comment]
@adishua @yehudarav save images in DB takes much space in memory, what is your image size?

**Comment by YehuditGrinwald** [comment]
@yehudarav Should look like editable table ?
![image](https://user-images.githubusercontent.com/24703036/90015466-51ec8a80-dcb1-11ea-8a07-b3ddffcbc139.png)

**Comment by YehuditGrinwald** [comment]
1. Add one more column:  "embedded on map" type- boolean.
2. bounds replace with - tow  objects - left corner {x,y}, right corner .
3. On edit row->replace "choose file" with open pop/extend:
row object details is required.
set the: image, corners (4 numbers), name.

![image](https://user-images.githubusercontent.com/24703036/95855718-850ad300-0d61-11eb-974c-d2212d3b641e.png)
